Feature/Demo store
rees46/demo-ios pull request #1
Opened 2024-07-03 11:35 UTC by DanielGreenEngineer

* https://github.com/rees46/planning/issues/822

2024-07-18 14:49 UTC, DanielGreenEngineer commented
@TorinAsakura PR готов, можно смотреть, архитектурно разнес по твоим наработкам

2024-07-18 19:24 UTC, TorinAsakura requested changes
Дальше не залезал, если в навигации столько проблем

2024-07-18 19:24 UTC, TorinAsakura commented on App/Navigation/Domain/NavigationManager.swift
> +    func resetSelection() {
он точно нам нужен? он же по сути ничего толком не делает, кроме сброса выбранной закладки

2024-07-18 19:24 UTC, TorinAsakura commented on App/Navigation/Presentation/View/BottomBarView.swift
Как-то подозрительно выглядит. Не то чтобы прям неверно, но чисто логически навигация и представление лучше бы разделить.

Модель навигации и сами вьюхи стоит держать отдельно. Лучше будет, если в Presentation у тебя будут экраны и соответствующие вьюхи, а в Navigation — логика переходов.

2024-07-18 19:24 UTC, TorinAsakura commented on App/Navigation/Presentation/View/BottomBarView.swift
> +    @EnvironmentObject var navigationManager: NavigationManager
Сразу же здесь чувствуется запах антифрендов. Используешь @EnvironmentObject, что вроде норм, но вот @State private var selectedTab уже не сильно нужен, ведь он дублирует navigationManager.selectedTab

2024-07-18 19:24 UTC, TorinAsakura commented on App/Navigation/Presentation/View/BottomBarView.swift
> +    var body: some View {
Теперь блок с табами. Твоя логика смены табов слишком раздута

2024-07-18 19:24 UTC, TorinAsakura commented on App/Navigation/Presentation/View/BottomBarView.swift
> +    }
```suggestion
    var body: some View {
    VStack {
        if !navigationManager.isBottomBarHidden {
            Spacer()
            
            HStack {
                TabBarButton(image: "MainTab", isSelected: navigationManager.selectedTab == .main)
                    .onTapGesture {
                        navigateTo(screen: HomeScreenView(), tab: .main)
                    }
                    .padding(.leading, 20)
                
                Spacer()
                
                TabBarButton(image: "CatalogTab", isSelected: navigationManager.selectedTab == .catalog)
                    .onTapGesture {
                        navigateTo(screen: ProductsScreenView(), tab: .catalog)
                    }
                
                Spacer()
                
                TabBarButton(image: "CartTab", isSelected: navigationManager.selectedTab == .cart)
                    .onTapGesture {
                        navigateTo(screen: CartScreenView(), tab: .cart)
                    }
                
                Spacer()
                
                TabBarButton(image: "SettingsTab", isSelected: navigationManager.selectedTab == .settings)
                    .onTapGesture {
                        navigateTo(screen: SettingsScreenView(), tab: .settings)
                    }
                    .padding(.trailing, 20)
            }
        }
    }
}

private func navigateTo<Content: View>(screen: Content, tab: ScreenType) {
    navigationManager.navigateTo(screen: AnyView(screen), selectedTab: tab)
}
```

2024-07-18 19:24 UTC, TorinAsakura commented on App/Navigation/Presentation/View/BottomBarView.swift
> +            Spacer().frame(height: 30)
зачем тут спейсер? кнопка не должна создавать внешние отступы, этим должен заниматься скрин

2024-07-18 19:24 UTC, TorinAsakura commented on App/mainSubView/UiUtils.swift
Код смешивает логику и представление

2024-07-18 19:24 UTC, TorinAsakura commented on App/mainSubView/UiUtils.swift
> +class HostingController: UIHostingController<AnyView> {
Использование UIHostingController и работа с statusBarStyle через наблюдателя (KVO) — это довольно костыльный способ. Давай подумаем, как можно улучшить этот подход.

2024-07-18 19:24 UTC, TorinAsakura commented on App/mainSubView/UiUtils.swift
> +import SwiftUI
я вижу это как-то так

- App/UI/Utils/StatusBarStyleKey.swift
- App/UI/Utils/HostingController.swift
- App/Extensions/View+StatusBar.swift

2024-07-18 19:24 UTC, TorinAsakura commented on App/ContentView.swift
> +        ZStack {
Твой ZStack сначала делает фон чёрным, а потом сверху накладывает белый фон. Это бессмысленно и может вызывать ненужные вычисления.

2024-07-18 19:24 UTC, TorinAsakura commented on App/ContentView.swift
> +                    .environmentObject(navigationManager)
Ты дважды добавляешь navigationManager в environmentObject, что избыточно и из-за чего код выглядит слегка костыльно

2024-07-18 19:24 UTC, TorinAsakura commented on App/ContentView.swift
> +        .statusBar(hidden: false)
Ты добавляешь статус-бар, но не используешь метод, который добавили раньше для управления его стилем

2024-07-18 19:24 UTC, TorinAsakura commented on App/DemoStoreApp.swift
> +            if showSplash {
Логика отображения Splash экрана: Использование @State для управления логикой отображения Splash экрана в корневом App — это не самый лучший подход. Лучше вынести это в отдельный view.

2024-07-18 19:24 UTC, TorinAsakura commented on App/DemoStoreApp.swift
> +                    .onAppear {
Асинхронный вызов в onAppear: Логика показа главного контента через DispatchQueue.main.asyncAfter выглядит как костыль.

2024-07-18 19:24 UTC, TorinAsakura commented on App/DemoStoreApp.swift
> +}
```suggestion
import SwiftUI

@main
struct DemoStoreApp: App {
    var body: some Scene {
        WindowGroup {
            SplashView()
        }
    }
}

struct SplashView: View {
    @State private var showSplash = true

    var body: some View {
        if showSplash {
            LaunchScreen()
                .edgesIgnoringSafeArea(.all)
                .onAppear {
                    DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
                        withAnimation {
                            showSplash = false
                        }
                    }
                }
        } else {
            ContentView()
        }
    }
}
```

2024-07-18 20:15 UTC, DanielGreenEngineer commented
@TorinAsakura Спасибо за критику, я ценю это! Мне действительно не хватает фундаментальных знаний и я благодарен за то, что ты мне их даёшь. 
Всё исправлю, это в моих интересах!

2024-07-21 10:31 UTC, DanielGreenEngineer commented on App/mainSubView/UiUtils.swift
Исправил. Не верно этот пакет и файл из директории

2024-07-21 10:33 UTC, DanielGreenEngineer commented on App/Navigation/Domain/NavigationManager.swift
> +class NavigationManager: ObservableObject {
Упустил этот момент, утащил в пакет навигации и поправил остальное в слое App

2024-07-21 10:34 UTC, DanielGreenEngineer commented on App/Navigation/Domain/NavigationManager.swift
> +    init() {
Соглашусь, исправил

2024-07-21 10:37 UTC, DanielGreenEngineer commented on App/Navigation/Domain/NavigationManager.swift
> +    func navigateTo<Content: View>(screen: Content, selectedTab: ScreenType? = .main) {
Попробовал визитор, не зашел он мне, сделал чуть проще, но лаконично по моему

2024-07-21 10:38 UTC, DanielGreenEngineer commented on App/Navigation/Domain/NavigationManager.swift
> +    func setToolbarHidden(hidden: Bool) {
Да, ты прав, исправил

2024-07-21 10:38 UTC, DanielGreenEngineer commented on App/Navigation/Domain/NavigationManager.swift
> +    func resetSelection() {
Не нужен, удалил

2024-07-21 10:39 UTC, DanielGreenEngineer commented on App/Navigation/Presentation/View/BottomBarView.swift
Раскидал, оставил чисто вью, остальное утащил в дату

2024-07-21 10:40 UTC, DanielGreenEngineer commented on App/Navigation/Presentation/View/BottomBarView.swift
> +    @EnvironmentObject var navigationManager: NavigationManager
Исправил

2024-07-21 10:41 UTC, DanielGreenEngineer commented on App/Navigation/Presentation/View/BottomBarView.swift
> +    var body: some View {
Исправил

2024-07-21 10:45 UTC, DanielGreenEngineer commented on App/Navigation/Presentation/View/BottomBarView.swift
> +            Spacer().frame(height: 30)
Исправил

2024-07-21 10:46 UTC, DanielGreenEngineer commented on App/mainSubView/UiUtils.swift
> +class HostingController: UIHostingController<AnyView> {
Это старая реализация. Не верно удалил из директории

2024-07-21 11:31 UTC, DanielGreenEngineer commented on App/ContentView.swift
> +        ZStack {
Расставил цвета по вьюхам

2024-07-21 11:35 UTC, DanielGreenEngineer commented on App/ContentView.swift
> +                    .environmentObject(navigationManager)
Исправил

2024-07-21 11:35 UTC, DanielGreenEngineer commented on App/ContentView.swift
> +        .statusBar(hidden: false)
Удалил эту строку, она лишняя, так как не кастомизирую статус бар

2024-07-21 11:47 UTC, DanielGreenEngineer commented on App/DemoStoreApp.swift
> +            if showSplash {
Вынес на сплеш экран

2024-07-21 12:44 UTC, DanielGreenEngineer commented on App/DemoStoreApp.swift
> +                    .onAppear {
Добавил простой таймер и установил его во всех местах где эмулирую загрузку

2024-07-21 12:55 UTC, DanielGreenEngineer commented
@TorinAsakura Привет. 
Все замечания исправил, теперь куда круче стало

2024-07-22 16:26 UTC, DanielGreenEngineer commented on App/mainSubView/UiUtils.swift
> +import SwiftUI
Удалил файл, так как не использую его более

2024-07-22 16:29 UTC, DanielGreenEngineer commented on App/Navigation/Presentation/View/BottomBarView.swift
> +    }
Не воспользовался этим примером, так как кардинально переделал структуру вьюхи и навигацию, разделив на основные экраны и второстепенные

2024-07-22 17:20 UTC, TorinAsakura requested changes

2024-07-22 17:20 UTC, TorinAsakura commented on App/Presentation/View/ContentView.swift
> +                .background(Color.white)
зачем он тут?

2024-07-22 17:20 UTC, TorinAsakura commented on Core/DI/SdkManager.swift
> +    private let SHOP_ID = "357382bf66ac0ce2f1722677c59511"
такие вещи нужно держать в переменных окружения

2024-07-22 17:20 UTC, TorinAsakura commented on Core/DI/SdkManager.swift
> +    private func initializeSDK() {
даже несмотря на то, что это синглтон, не использовать тут DI, когда мы…используем DI в проекте - странно

2024-07-22 17:20 UTC, TorinAsakura commented on Core/Resources/Localizable.xcstrings
> +{
ресурсы не являются частью кора, их надо вынести наверх

2024-07-22 17:20 UTC, TorinAsakura commented on Core/Core.h
> +//  Created by Daniel Green on 2024-07-18.
комменты

2024-07-22 17:20 UTC, TorinAsakura commented on Core/Utils/RatingConverter.swift
-> Presentation/Views/RatingView.swift

2024-07-22 17:20 UTC, TorinAsakura commented on Core/Utils/RemoteImageLoader.swift
> +class RemoteImageLoader: ObservableObject {
-> Presentation/Views/RemoteImageView.swift

2024-07-23 19:53 UTC, DanielGreenEngineer commented on App/Navigation/Data/ScreenType.swift
> +
Удалил

2024-07-23 19:54 UTC, DanielGreenEngineer commented on App/Navigation/Data/ScreenType.swift
> +enum RootScreenType {
Переименовал

2024-07-23 19:54 UTC, DanielGreenEngineer commented on App/Navigation/Data/TabItem.swift
> +import SwiftUI
Исправил и переместил

2024-07-23 19:56 UTC, DanielGreenEngineer commented on App/Navigation/Domain/Repository/ScreenTypeProvider.swift
> +import Foundation
Переместил в пакет протоколов в навигации и разделил логику, чтобы не смешивалось

2024-07-23 19:57 UTC, DanielGreenEngineer commented on App/Navigation/Domain/Repository/ScreenTypeProvider.swift
> +import SwiftUI
Унес провайдер в протокол пакет, а разширения переместил в экраны по твоему совету

2024-07-23 19:57 UTC, DanielGreenEngineer commented on App/Navigation/Presentation/View/BottomBarView.swift
> +struct BottomBarView: View {
Использовал эту структуру для модуля апп

2024-07-23 19:57 UTC, DanielGreenEngineer commented on App/Navigation/NavigationManager.swift
> +    private let rootScreenInitializers: [RootScreenType: () -> AnyView] = [
Вынес

2024-07-23 19:58 UTC, DanielGreenEngineer commented on App/Presentation/View/ContentView.swift
> +                .background(Color.white)
Вынес это в отдельное вью, что не терять лаконичность

2024-07-23 19:59 UTC, DanielGreenEngineer commented on Core/DI/SdkManager.swift
> +    private let SHOP_ID = "357382bf66ac0ce2f1722677c59511"
Добавил всё возможное в переменные окружения

2024-07-23 19:59 UTC, DanielGreenEngineer commented on Core/Resources/Localizable.xcstrings
> +{
Вынес

2024-07-23 19:59 UTC, DanielGreenEngineer commented on Core/Core.h
> +//  Created by Daniel Green on 2024-07-18.
Удалил

2024-07-23 19:59 UTC, DanielGreenEngineer commented on Core/Utils/RatingConverter.swift
Перенес

2024-07-23 19:59 UTC, DanielGreenEngineer commented on Core/Utils/RemoteImageLoader.swift
> +class RemoteImageLoader: ObservableObject {
Перенес

2024-07-24 15:16 UTC, DanielGreenEngineer commented on Core/DI/SdkManager.swift
> +    private func initializeSDK() {
Согласен. 
Добавил актуальный резолвер и теперь при необходимости будем инжектить. 
Все таки резолвер классная штука, коин напоминает

2024-07-24 16:23 UTC, DanielGreenEngineer commented
@TorinAsakura Все замечания исправил, лишнее выкинул, новое привнёс. Избавился от лишних синглтонов, всё что было можно и нужно перевёл на DI. 
Так же все коды для инициализации сдк, загрузки блоков товаров и прочее, всё утащил в переменные окружение и под них вывел отдельный файл в кор слое. 
Разобрался с резолвером, удобная штука, напоминает Koin. 
Возможно, что то упустил в расположении файлов, жду критики

2024-07-30 15:37 UTC, TorinAsakura requested changes
1. Рассмотри использование Lazy*Stack
2. Если со структурой мы более или менее разобрались то UI как был разбросанной кучей так и остался - вот пример того, как он должен формироваться https://github.com/torin-asakura/dream-team/tree/master/ui - зависимости этих пакетов я уж думаю сам найдёшь по коду
3. Далее, у тебя во вьюхах экранов опять происходит стройка, хотя я тебе уже который раз объяснял, что во вьюхах ты должен просто импортировать куски от этих экранов и производить только их сборку, а вся стройка должна происходит внутри этих кусков - вот пример как у нас выглядят страницы (структурно) https://github.com/torin-asakura/dream-team/tree/master/landing/pages - такой же смысл должен быть и тут
4. Если посмотришь на уровень выше - увидишь фрагменты - это из области микрофронтов, кроме самих микрофронтов, но, суть примерно та же - каждый бизнес кусок поделён на фрагменты, вся стройка этих кусков происходит внутри фрагментов из юай компонентов которые живут также отдельным слоем, а в самих страничках происходит только сборка из фрагментов, всё

2024-07-30 15:37 UTC, TorinAsakura commented on App/Models/TabItem.swift
> +struct TabItem: Identifiable {
на такие стракты можешь добавлять суффикс для файла соответствующий

2024-07-30 15:37 UTC, TorinAsakura commented on App/Views/BottomBar/BottomBarView.swift
> +                .foregroundColor(isSelected ? .white : .gray)
полагаю цвета нужно вынести в отдельные константы в слой ui, да?

2024-07-30 15:37 UTC, TorinAsakura commented on App/Views/Screens/CartScreenView.swift
> +                viewModel.loadRecommenderRecommendations(currentProductId: "665")
почему захардкожен айди продукта?

2024-07-30 15:37 UTC, TorinAsakura commented on App/Views/Screens/CartScreenView.swift
> +                    ).frame(height: 250)
что за засилие волшебных чисел?

2024-07-30 15:37 UTC, TorinAsakura commented on App/Views/Screens/ProductsScreenView.swift
> +            }
эти принты для кого?

2024-07-30 15:38 UTC, TorinAsakura commented
@DanielGreenEngineer также хочу обратить твоё внимание, что енамы ты именуешь через конвенциональный нейминг, а протоколы и стракты нет, стракты вообще не имменуешь

2024-08-05 07:51 UTC, DanielGreenEngineer commented on App/Views/Screens/ProductsScreenView.swift
> +            }
Вешал для себя, удалил

2024-08-05 07:52 UTC, DanielGreenEngineer commented on App/Views/Screens/CartScreenView.swift
> +                viewModel.loadRecommenderRecommendations(currentProductId: "665")
Исправил

2024-08-05 07:52 UTC, DanielGreenEngineer commented on App/Views/BottomBar/BottomBarView.swift
> +                .foregroundColor(isSelected ? .white : .gray)
Вынес

2024-08-05 07:53 UTC, DanielGreenEngineer commented on App/Models/TabItem.swift
> +struct TabItem: Identifiable {
Добавил суффиксы всем страктам, так же и для протоколов

2024-08-05 13:04 UTC, DanielGreenEngineer commented on App/Views/Screens/CartScreenView.swift
> +                    ).frame(height: 250)
Все возможные MagicNumbers вынес в соответствующие константы с размерами

2024-08-05 13:05 UTC, DanielGreenEngineer commented
> @DanielGreenEngineer также хочу обратить твоё внимание, что енамы ты именуешь через конвенциональный нейминг, а протоколы и стракты нет, стракты вообще не имменуешь

Добавил суффиксы всем страктам, а протоколы оставил без суффиксов, у них в имени класса указал "Протокол"

2024-08-05 13:07 UTC, DanielGreenEngineer commented
@TorinAsakura Все замечания исправил, вьюхи разбил на мелкие кусочки, так же раскидал их по пакетам в соответствующих фичах. Цвета и размеры утащил в константы.

2024-08-06 16:43 UTC, TorinAsakura requested changes
Продолжаем марлезонский баллет…

2024-08-06 16:43 UTC, TorinAsakura commented on App/Navigation/Protocols/ScreenTypeProviderProtocol.swift
*.protocol.swift

2024-08-06 16:43 UTC, TorinAsakura commented on App/Views/BottomBar/button/TabBarButton.swift
> +struct TabBarButton: View {
что такое TabBarButton? Покажи мне её пожалуйста на дизайне, в толк не возьму что это такое

2024-08-06 16:43 UTC, TorinAsakura commented on App/Views/Screens/CartScreenView.struct.swift
1. CartScreenView отвечает за отображение списка товаров, общую стоимость, кнопки навигации и рекомендации - таков был план или я чот не понимаю?
2. Обработка состояния загрузки и рекомендации, полагаю, нужно вынести в отдельные компоненты чтобы их не копипастить, да?

2024-08-06 16:43 UTC, TorinAsakura commented on App/Views/ToolBar/ToolbarView.struct.swift
>                          .foregroundColor(.black)
а это ты кому оставил?

2024-08-06 16:43 UTC, TorinAsakura commented on Core/Presentation/Views/RatingConverter.struct.swift
1. Где тут конвертер?
2. Зачем тут инициализатор?

2024-08-06 16:43 UTC, TorinAsakura commented on Core/Resources/Colors/AppColors.struct.swift
я ведь тебе написал куда это нужно вынести, это должен был быть слой ui/**/*, зачем ты это положил в ресурсы? Я ведь тебе даже линк на нашу дизайн-систему приложил!

|-- UI/
|   |-- Colors/
|   |   |-- AppColors.swift
|   |
|   |-- Sizes/
|   |   |-- Sizes.swift
|   |
|   |-- Fonts/
|       |-- Typography.swift

Примерно так

2024-08-06 16:43 UTC, TorinAsakura commented on Feature/Cart/Presentation/View/Button/NavigationButtonsView.struct.swift
Снова какой-то фарш из подмены понятий…Что такое КнопкиНавигации? И почему у них отдельная вьюха? Ничего не понимаю

2024-08-06 16:43 UTC, TorinAsakura commented on Feature/Cart/Presentation/View/Button/RemoveButtonView.struct.swift
Вот опять…Что это? Что это за кнопка мифическая? Вот как должны кнопки выглядеть https://github.com/atls/hyperion/tree/master/ui-parts/button/src

2024-08-07 13:00 UTC, DanielGreenEngineer commented on App/Navigation/Protocols/ScreenTypeProviderProtocol.swift
Добавил суффиксы всем протоколам

2024-08-07 13:02 UTC, DanielGreenEngineer commented on App/Views/BottomBar/button/TabBarButton.swift
> +struct TabBarButton: View {
Это кнопка нижнего бара навигации, ios-сники её обычно так именуют, . Переименовал соответствующе, чтобы указать её принадлежность

2024-08-07 14:20 UTC, DanielGreenEngineer commented on App/Views/ToolBar/ToolbarView.struct.swift
>                          .foregroundColor(.black)
Упустил это. Вставил размеры из констант

2024-08-07 14:24 UTC, DanielGreenEngineer commented on Core/Presentation/Views/RatingConverter.struct.swift
- Переименовал. Забыл выкинуть "конвертер" из названия после разделения файлов. 
- Инициализатор служит для подмены значений, так как сейчас их у нас нет, я устанавливаю радномное значение, чтобы показать наличие рейтинга.

2024-08-07 14:26 UTC, DanielGreenEngineer commented on Core/Resources/Colors/AppColors.struct.swift
Видимо я забыл и по этому закинул их по аналогии с андроидом в общую кучу к ресурсам. Сейчас вынес в пакет UI и утащил размеры текста в "Типографию"

2024-08-07 14:32 UTC, DanielGreenEngineer commented on Feature/Cart/Presentation/View/Button/NavigationButtonsView.struct.swift
Согласен, тупое название, заменил на соответствующее и не вводящее в заблуждение

2024-08-07 14:33 UTC, DanielGreenEngineer commented on Feature/Cart/Presentation/View/Button/RemoveButtonView.struct.swift
Поместил её прямо на экран, так как дежать под неё целое вью не разумно в данный момент

2024-08-07 15:54 UTC, DanielGreenEngineer commented on App/Views/Screens/CartScreenView.struct.swift
- Нейминг моих вьюх не отражал картину верным образом, в связи с этим внес изменения в имена: Список товаров в корзине, Общая стоимость товаров, Кнопки для оплаты или продолжение покупок и блок рекомендаций
- Обьеденил загрузку и остальные элементы, чтобы не утраивать дискотеку на экране

2024-08-07 21:26 UTC, merged