Fix/search screen
rees46/demo-ios pull request #3
Opened 2024-08-09 10:10 UTC by DanielGreenEngineer

- https://github.com/rees46/planning/issues/1427

2024-08-09 13:49 UTC, TorinAsakura requested changes

2024-08-09 13:49 UTC, TorinAsakura commented on Feature/Search/Presentation/View/Button.struct/SearchViewAllProductsButton.struct.swift
зачем ты прибил кнопку к контексту?

2024-08-09 13:49 UTC, TorinAsakura commented on Feature/Search/Presentation/View/List/SearchResultProductGridView.struct.swift
> +            LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 16) {
что за 16?

2024-08-09 13:49 UTC, TorinAsakura commented on Feature/Search/Presentation/View/List/SearchResultProductGridView.struct.swift
почему у тебя грид вью в листе?

2024-08-09 15:36 UTC, DanielGreenEngineer commented on Feature/Search/Presentation/View/List/SearchResultProductGridView.struct.swift
> +            LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 16) {
Упустил это, заменил на константное значение

2024-08-09 15:36 UTC, DanielGreenEngineer commented on Feature/Search/Presentation/View/Button.struct/SearchViewAllProductsButton.struct.swift
Случайно видимо зацепил, когда стракт именовал. Исправил

2024-08-09 18:32 UTC, TorinAsakura requested changes

2024-08-09 18:32 UTC, TorinAsakura commented on Feature/Search/Presentation/View/List/SearchResultProductGridView.struct.swift
грид это сетка, как сетка может быть списком?

2024-08-09 19:05 UTC, DanielGreenEngineer commented on Feature/Search/Presentation/View/List/SearchResultProductGridView.struct.swift
Переместил в отдельный пакет

2024-08-12 11:11 UTC, TorinAsakura approved these changes

2024-08-12 11:20 UTC, TorinAsakura approved these changes

2024-08-12 11:21 UTC, merged